@rem Generated by the Gradle wrapper
@rem ----------------------------
@echo off
setlocal
set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
set APP_HOME=%DIRNAME%..\
set GRADLE_WRAPPER_JAR=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar
set JAVA_EXE=%JAVA_HOME%\bin\java.exe
if not exist "%JAVA_EXE%" (
  set JAVA_EXE=java
)
"%JAVA_EXE%" -jar "%GRADLE_WRAPPER_JAR%" %*
