#!/usr/bin/env sh
#
# Gradle start up script for UNIX
#
# Generated by the Gradle wrapper.
#
APP_NAME="Gradle"
APP_BASE_NAME="gradlew"
APP_HOME=
# Resolve links - $0 may be a link
PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`"/""$link"
  fi
done
SAVED="`pwd`"
cd `dirname "$PRG"`/..
APP_HOME="`pwd -P`"
cd "$SAVED"
# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m"
APP_ARGS=""
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD=`which java 2>/dev/null`
fi
if [ -z "$JAVACMD" ] ; then
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." 1>&2
    exit 1
fi
exec "$JAVACMD" $DEFAULT_JVM_OPTS -jar "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" "$@"
